### PR TITLE
Adding CONTRIBUTING.md & CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by 201B153**
for Issues #9  and #8

### CODE REVIEW

**Review by 201B153 — COMMENTED** [review]
Approve it.

**Review by Clash-ion — APPROVED** [review]
lgtm

**Comment by Sonali-Rajput** [comment]
won't it be better if you make a new branch for every new PR other than main

**Comment by Clash-ion** [comment]
> won't it be better if you make a new branch for every new PR other than main

@201B153

**Comment by 201B153** [comment]
nope!
there will be multiple branches which can lead to PR duplicacy.
It is better to wait for one PR merge then merge another one.
It will keep the main branch safe from conflicts and also helps in better management.

**Comment by sonali-rajput** [comment]
It is better to have a new branch while making a PR other than main because still a lot of organizations use the git flow method where they have three env as dev stage prod etc, but nowadays trunk-based development is considered more, also it will not create duplicacy for us as we have only main branch.

**Comment by sonali-rajput** [comment]
I want you to make a PR as 201B153:new-branch-name rather than this 201B153:main

**Comment by mstomar698** [comment]
OK 🙏,
from next time I will make  branch than send PR.
please accept this PR.
Thank you
Mayank Singh Tomar

**Comment by sonali-rajput** [comment]
the other PR is accepted already, this PR is closed

**Pull request closed without merging**
