### PR TITLE
Add dockerfile for go app

### PR DESCRIPTION
**Pull request by sonali-rajput**
Description:
Add Dockerfile for Go application

### CODE REVIEW

**Review by Clash-ion — CHANGES_REQUESTED** [review]
you can also take a look at this...
https://levelup.gitconnected.com/golang-optimizing-docker-image-size-from-2-4-gb-to-100-mb-using-docker-multi-stage-build-process-5b808f20e808
@Sonali-Rajput

**Review by 201B153 — APPROVED** [review]
👍

**Review by Clash-ion — APPROVED** [review]
lgtm

**Comment by mukul-kr** [comment]
resolves #2

**Pull request merged**
